version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

# TODO добавить сервисы

cars-service:
    build:
      context: .
      dockerfile: Dockerfile.cars
    environment:
      PORT: "8070"
    ports:
      - "8070:8070"

rental-service:
  build:
    context: .
    dockerfile: Dockerfile.rental
  environment:
    PORT: "8060"
  ports:
    - "8060:8060"

payment-service:
  build:
    context: .
    dockerfile: Dockerfile.payment
  environment:
    PORT: "8050"
  ports:
    - "8050:8050"

gateway-service:
  build:
    context: .
    dockerfile: Dockerfile.gateway
  environment:
    PORT: "8080"
  ports:
    - "8080:8080"
  depends_on:
    - cars-service
    - rental-service
    - payment-service


volumes:
  db-data: